### ISSUE TITLE
Go through all the titles on the entire site and make sure they match the figma (if font is too big/small, use your judgment on sizing))

### ISSUE THREAD

**Issue by JoeSilla** [GianlucaP106/devpromedia#11]
Service Title (ex. Web Development in orange) : Inter Medium 24 font
Titles : Inter Regular 40 font 
Text: Inter Medium 20 font
Box Description: Inter Medium 16 font

**Comment by GianlucaP106** [comment]
I think i did everything, lmk if smtg looks off
