### ISSUE TITLE
Add flying starts to all black sections (top of page, newsletter and footer)

### ISSUE THREAD

**Issue by JoeSilla** [GianlucaP106/devpromedia#15]
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.dev/svgjs" viewBox="0 0 800 800"><rect width="100%" height="100%" fill="#1c1c1d"></rect><g fill="#ff5e37"><rect width="636" height="1" x="184" y="519.5" rx="0.5" transform="rotate(46, 502, 520)" opacity="0.68"></rect><rect width="402" height="1" x="334" y="75.5" rx="0.5" transform="rotate(46, 535, 76)" opacity="0.62"></rect><rect width="560" height="1" x="-217" y="55.5" rx="0.5" transform="rotate(46, 63, 56)" opacity="0.93"></rect><rect width="420" height="1" x="338" y="238.5" rx="0.5" transform="rotate(46, 548, 239)" opacity="0.74"></rect><rect width="316" height="1" x="-78" y="432.5" rx="0.5" transform="rotate(46, 80, 433)" opacity="0.72"></rect><rect width="783" height="1" x="-69.5" y="689.5" rx="0.5" transform="rotate(46, 322, 690)" opacity="0.40"></rect><rect width="144" height="1" x="29" y="166.5" rx="0.5" transform="rotate(46, 101, 167)" opacity="0.65"></rect><rect width="560" height="1" x="82" y="89.5" rx="0.5" transform="rotate(46, 362, 90)" opacity="0.53"></rect><rect width="252" height="1" x="402" y="714.5" rx="0.5" transform="rotate(46, 528, 715)" opacity="0.74"></rect><rect width="169" height="1" x="233.5" y="255.5" rx="0.5" transform="rotate(46, 318, 256)" opacity="0.51"></rect><rect width="243" height="1" x="-15.5" y="719.5" rx="0.5" transform="rotate(46, 106, 720)" opacity="0.23"></rect><rect width="849" height="1" x="18.5" y="305.5" rx="0.5" transform="rotate(46, 443, 306)" opacity="0.51"></rect><rect width="674" height="1" x="375" y="517.5" rx="0.5" transform="rotate(46, 712, 518)" opacity="0.83"></rect><rect width="544" height="1" x="399" y="197.5" rx="0.5" transform="rotate(46, 671, 198)" opacity="0.65"></rect><rect width="871" height="1" x="-128.5" y="414.5" rx="0.5" transform="rotate(46, 307, 415)" opacity="0.65"></rect><rect width="173" height="1" x="-3.5" y="322.5" rx="0.5" transform="rotate(46, 83, 323)" opacity="0.82"></rect><rect width="300" height="1" x="-57" y="567.5" rx="0.5" transform="rotate(46, 93, 568)" opacity="0.64"></rect><rect width="719" height="1" x="353.5" y="696.5" rx="0.5" transform="rotate(46, 713, 697)" opacity="0.44"></rect><rect width="727" height="1" x="266.5" y="373.5" rx="0.5" transform="rotate(46, 630, 374)" opacity="0.09"></rect><rect width="710" height="1" x="-155" y="266.5" rx="0.5" transform="rotate(46, 200, 267)" opacity="0.86"></rect><rect width="56" height="1" x="678" y="45.5" rx="0.5" transform="rotate(46, 706, 46)" opacity="0.44"></rect><rect width="547" height="1" x="483.5" y="143.5" rx="0.5" transform="rotate(46, 757, 144)" opacity="0.25"></rect><rect width="129" height="1" x="690.5" y="332.5" rx="0.5" transform="rotate(46, 755, 333)" opacity="0.54"></rect><rect width="480" height="1" x="-206" y="220.5" rx="0.5" transform="rotate(46, 34, 221)" opacity="0.64"></rect><rect width="152" height="1" x="177" y="528.5" rx="0.5" transform="rotate(46, 253, 529)" opacity="0.25"></rect><rect width="130" height="1" x="141" y="82.5" rx="0.5" transform="rotate(46, 206, 83)" opacity="0.89"></rect></g></svg>

or use this i think i copied the svg there^ 

![ffflurry](https://user-images.githubusercontent.com/108885417/235320703-fcaee999-1d8b-4f52-9d88-9428154507e9.svg)

**Comment by GianlucaP106** [comment]
#### tbh im not sure about this anymore, can you design an alternative way to spice up the home page ?
