### ISSUE TITLE
add the mailchimp image and voysis email marketing example (in discord)

### ISSUE THREAD

**Issue by JoeSilla** [GianlucaP106/devpromedia#16]
Check out figma if you need 

<img width="1184" alt="Screenshot 2023-04-29 at 6 54 40 PM" src="https://user-images.githubusercontent.com/108885417/235327324-298e5373-b1fc-49fa-99cc-22e3c208500d.png">

**Comment by GianlucaP106** [comment]
put all the images that go on the website in a zip and send it me
