### ISSUE TITLE
Add IG, FB, and LinkedIn icons and link them to us 

### ISSUE THREAD

**Issue by JoeSilla** [GianlucaP106/devpromedia#26]
![Screenshot 2023-05-04 at 3 26 59 PM](https://user-images.githubusercontent.com/108885417/236309478-c2046bdc-b294-4f51-a23d-c2f4b62c209f.png)

**Comment by GianlucaP106** [comment]
send me the icons and the links

**Comment by JoeSilla** [comment]
[Socials.zip](https://github.com/GianlucaP106/devpromedia/files/11401712/Socials.zip)

**Comment by JoeSilla** [comment]
Instagram: https://www.instagram.com/devpro_media/
Facebook: https://www.facebook.com/profile.php?id=100087679507737
LinkedIn: https://www.linkedin.com/company/devpromedia/?viewAsMember=true
