### ISSUE TITLE
Also add the balls on all the black spots on every page

### ISSUE THREAD

**Issue by JoeSilla** [GianlucaP106/devpromedia#39]
for example on the homepage:

<img width="1038" alt="Screenshot 2023-05-20 at 9 40 14 PM" src="https://github.com/GianlucaP106/devpromedia/assets/108885417/480377e7-d5d3-4f6f-8eb0-6d9e19d3add6">

<img width="836" alt="Screenshot 2023-05-20 at 9 40 23 PM" src="https://github.com/GianlucaP106/devpromedia/assets/108885417/867ff055-629f-4ea3-b9c4-a61d0597a52f">

<img width="1387" alt="Screenshot 2023-05-20 at 9 40 32 PM" src="https://github.com/GianlucaP106/devpromedia/assets/108885417/b56b857a-fec2-4e9d-8111-5ad47108eaab">

**Comment by GianlucaP106** [comment]
I personally think its better only on footer and top
