### ISSUE TITLE
for the arrows, everytime it changes product it changes position (check it out on mobile) can we have it all like the going voip run? if you can make it stationary or smt

### ISSUE THREAD

**Issue by JoeSilla** [GianlucaP106/devpromedia#40]
<img width="374" alt="Screenshot 2023-05-20 at 9 42 19 PM" src="https://github.com/GianlucaP106/devpromedia/assets/108885417/da9aa745-a872-4257-a68e-b8829560fe1d">

**Comment by GianlucaP106** [comment]
### im not sure what you mean, lets go over it tomorrow night at the meeting
